<a href="https://colab.research.google.com/github/akanksha0911/DL_Tensors-PyTorch/blob/main/DL_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Tesnor Basics**

Tensors are multi-dimensional arrays with a uniform type (called a dtype). You can see all supported dtypes at tf.dtypes.DType.

If you're familiar with NumPy, tensors are (kind of) like np.arrays.

All tensors are immutable like Python numbers and strings: you can never update the contents of a tensor, only create a new one.

In [1]:
import tensorflow as tf

In [2]:
print('tf version is: ',tf.__version__)
print('tf executing: ',tf.executing_eagerly())

tf version is:  2.8.0
tf executing:  True


1. "scalar" or "rank-0" tensor . A scalar contains a single value, and no "axes".

In [3]:
rank0 = tf.constant(4)
print(rank0)

tf.Tensor(4, shape=(), dtype=int32)


2. vector" or "rank-1" tensor is like a list of values. A vector has one axis:




In [4]:
rank1 = tf.constant([1,2,3])
print(rank1)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [5]:
# Let's make this a float tensor
rank1 = tf.constant([1.0,2.0,3.0])
print(rank1)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


3. A "matrix" or "rank-2" tensor has two axes:

In [6]:
rank2 = tf.constant([[1,2],[3,4],[6,5]])
print(rank2)

tf.Tensor(
[[1 2]
 [3 4]
 [6 5]], shape=(3, 2), dtype=int32)


4. Tensors may have more axes; here is a tensor with three axes:

In [7]:
rankn = tf.constant([[[1,2,3],
                     [3,2,4]],
                    [[2,1,3],
                     [4,2,6]],
                    [[1,6,2],
                     [3,5,2]],]
                    )
print(rankn)

tf.Tensor(
[[[1 2 3]
  [3 2 4]]

 [[2 1 3]
  [4 2 6]]

 [[1 6 2]
  [3 5 2]]], shape=(3, 2, 3), dtype=int32)


we can convert a tensor to a NumPy array either using np.array or the tensor.numpy method

In [8]:
import numpy as np

In [9]:
np.array(rank2)

array([[1, 2],
       [3, 4],
       [6, 5]], dtype=int32)

In [10]:
rankn.numpy()

array([[[1, 2, 3],
        [3, 2, 4]],

       [[2, 1, 3],
        [4, 2, 6]],

       [[1, 6, 2],
        [3, 5, 2]]], dtype=int32)

instantiate TF:  TF provides a number of functions that instantiate basic tensors in memory. The simplest of these are tf.zeros() and tf.ones().

In [11]:
tf_ones = tf.ones([3,2,4])
print(tf_ones)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(3, 2, 4), dtype=float32)


In [12]:
tf_zero = tf.zeros([3,2,4,5])
print(tf_zero)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(3, 2, 4, 5), dtype=float32)


**about shapes**
Tensors have shapes. Some vocabulary:

Shape: The length (number of elements) of each of the axes of a tensor.
Rank: Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
Axis or Dimension: A particular dimension of a tensor.
Size: The total number of items in the tensor, the product shape vector.

In [13]:
print('Type of every element:',tf_zero.dtype)

Type of every element: <dtype: 'float32'>


In [14]:
print('Number of axes:',tf_zero.ndim)

Number of axes: 4


In [15]:
print('Shape of the tensor:', tf_zero.shape)

Shape of the tensor: (3, 2, 4, 5)


In [16]:
print('Total number of elements: 3*2*4*5:',tf.size(tf_zero).numpy())

Total number of elements: 3*2*4*5: 120


In [17]:
y = tf.ones((1,5,3,4))
print(y)

tf.Tensor(
[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]], shape=(1, 5, 3, 4), dtype=float32)


##**Operations with Tensors**


1. Indexing


An index is a numerical representation of an item’s position in a sequence. This sequence can refer to many things: a list, a string of characters, or any arbitrary sequence of values.
indexes start at 0
negative indices count backwards from the end
colons, :, are used for slices: start:stop:step

In [18]:
rank_1 = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1)

tf.Tensor([ 0  1  1  2  3  5  8 13 21 34], shape=(10,), dtype=int32)


In [19]:
print("First element is:",rank_1[0].numpy())

First element is: 0


In [20]:
print('Last element is:',rank_1[-1].numpy())

Last element is: 34


In [21]:
print("Elements in between the 1st and the last are:",
  rank_1[1:-1].numpy())

Elements in between the 1st and the last are: [ 1  1  2  3  5  8 13 21]


In [22]:
print("Everything:", rank_1[:].numpy())       #copy

Everything: [ 0  1  1  2  3  5  8 13 21 34]


In [23]:
print("Reversed:", rank_1[::-1].numpy())

Reversed: [34 21 13  8  5  3  2  1  1  0]


In [24]:
#Multi-axis indexing
#Higher rank tensors are indexed by passing multiple indices.The exact same rules as in the single-axis case apply to each axis independently.


print(rank2.numpy())

[[1 2]
 [3 4]
 [6 5]]


In [25]:
# Pull out a single value from a 2-rank tensor
print(rank2[1, 1].numpy())

4


In [26]:
print("Second row:", rank2[1, :].numpy())

Second row: [3 4]


In [27]:
print("Last row:", rank2[-1, :].numpy())

Last row: [6 5]


**Manipulating Shapes**


The tf.reshape does not change the order of or the total number of elements in the tensor, and so it can reuse the underlying data buffer. This makes it a fast operation independent of how big of a tensor it is operating on.


In [28]:
x = tf.constant([[1], [2], [3]])
print(x)  

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


In [29]:
# You can reshape a tensor to a new shape.
# Note that you're passing in a list

reshaped = tf.reshape(x, [1, 3])
print(reshaped)

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [30]:
# If we pass -1 passed in the `shape` argument, then we flatten our Tensor.
print('The shape of the flattened Tensor object is:', tf.reshape(x, [-1]))

The shape of the flattened Tensor object is: tf.Tensor([1 2 3], shape=(3,), dtype=int32)


Reshaping will "work" for any new shape with the same total number of elements, but it will not do anything useful if you do not respect the order of the axes.



**Basic Operations with Tensors**

You can easily do basic math operations on tensors such as:

  Addition
  Element-wise Multiplication
  Matrix Multiplication
  Finding the Maximum or Minimum
  Finding the Index of the Max Element
  Computing Softmax Value

In [31]:
a = tf.constant([[2, 4], 
                 [6, 8]], dtype=tf.float32)
b = tf.constant([[1, 3], 
                 [5, 7]], dtype=tf.float32)

print(a)
print(b)

tf.Tensor(
[[2. 4.]
 [6. 8.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 3.]
 [5. 7.]], shape=(2, 2), dtype=float32)


In [32]:
add_tensors = tf.add(a,b)
print(add_tensors)

tf.Tensor(
[[ 3.  7.]
 [11. 15.]], shape=(2, 2), dtype=float32)


In [33]:
# We can use `tf.multiply()` function and pass the Tensors as arguments.
multiply_tensors = tf.multiply(a,b)
print(multiply_tensors)

tf.Tensor(
[[ 2. 12.]
 [30. 56.]], shape=(2, 2), dtype=float32)


In [34]:
# We can use `tf.matmul()` function and pass the Tensors as arguments.
matmul_tensors = tf.matmul(a,b)
print(matmul_tensors)

tf.Tensor(
[[22. 34.]
 [46. 74.]], shape=(2, 2), dtype=float32)


In [35]:
# Finding the Maximum or Minimum is possible with `tf.reduce_max()` and `tf.reduce_min()` function
print("The Max value of the tensor object b is:",
  tf.reduce_max(b).numpy())

# Finding the Index of the Max Element is possible with `tf.argmax()` function
print("The index position of the max element of the tensor object b is:",
  tf.argmax(b).numpy())

# Computing softmax is possible with `tf.nn.softmax()` function
print("The softmax computation result of the tensor object b is:",
  tf.nn.softmax(b).numpy())

The Max value of the tensor object b is: 7.0
The index position of the max element of the tensor object b is: [1 1]
The softmax computation result of the tensor object b is: [[0.11920292 0.880797  ]
 [0.11920292 0.880797  ]]


Broadcasting

When we try to do combined operations using multiple Tensor objects, the smaller Tensors can stretch out automatically to fit larger tensors, just as NumPy arrays

In [36]:
m = tf.constant([5])

n = tf.constant([[1,2],[3,4]])

print(m)
print(n)

tf.Tensor([5], shape=(1,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [37]:
print(tf.multiply(m, n))

tf.Tensor(
[[ 5 10]
 [15 20]], shape=(2, 2), dtype=int32)


##**Types of Tensors**

Ragged Tensors
String Tensors
Sparse Tensors

In [38]:
#Ragged tensors are tensors with different numbers of elements along the size axis
ragged_list = [[1, 2, 3],[4, 5],[6]]

ragged_tensor = tf.ragged.constant(ragged_list)

print(ragged_tensor)

<tf.RaggedTensor [[1, 2, 3], [4, 5], [6]]>


In [39]:
string_tensor = tf.constant(["With this", 
                             "code, I am", 
                             "creating a String Tensor"])

print(string_tensor)

tf.Tensor([b'With this' b'code, I am' b'creating a String Tensor'], shape=(3,), dtype=string)


In [40]:
#Sparse Tensors are rectangular Tensors for sparse data. When you have holes (i.e., Null values) in your data, Sparse Tensors are to-go objects


sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [2, 2], [4, 4]], 
                                       values=[25, 50, 100], 
                                       dense_shape=[5, 5])

# We can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

tf.Tensor(
[[ 25   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0  50   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0 100]], shape=(5, 5), dtype=int32)


##**tf.einsum**

C[i,k] = sum_j A[i,j] * B[j,k]. 

The corresponding einsum equation is:

ij,jk->ik

In [41]:
# Matrix multiplication


m0 = tf.random.normal(shape=[2, 3])
m1 = tf.random.normal(shape=[3, 5])
e = tf.einsum('ij,jk->ik', m0, m1)
# output[i,k] = sum_j m0[i,j] * m1[j, k]
print(e.shape)


(2, 5)


In [42]:
# Dot product

u = tf.random.normal(shape=[5])
v = tf.random.normal(shape=[5])
e = tf.einsum('i,i->', u, v)  # output = sum_i u[i]*v[i]
print(e)


tf.Tensor(1.9952836, shape=(), dtype=float32)


In [43]:
u = tf.random.normal(shape=[3])
v = tf.random.normal(shape=[5])
e = tf.einsum('i,j->ij', u, v)  # output[i,j] = u[i]*v[j]
print(e.shape)


(3, 5)


In [44]:
m = tf.ones(2,3)
e = tf.einsum('ij->ji', m0)  # output[j,i] = m0[i,j]
print(e.shape)

(3, 2)
